title: Victor Szoltysek
email: victor_szoltysek@me.com
description: >- 
  Bits of code and pieces of my mind.
baseurl: ""
url: "https://www.victorszoltysek.com" # the base hostname & protocol for your site
theme: minima
linkedin_url: https://www.linkedin.com/in/victorszoltysek/
github_username:  vicsz
slideshare_url: https://www.slideshare.net/VictorSzoltysek
