title: My Awesome Site
email: my-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my awesome blog using Beautiful Jekyll.
baseurl: ""
url: "https://www.victorszoltysek.com" # the base hostname & protocol for your site
theme: minima
linkedin_url: https://www.linkedin.com/in/victorszoltysek/
github_username:  vicsz
slideshare_url: https://www.slideshare.net/VictorSzoltysek
