title: My Awesome Site
email: my-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my awesome blog using Beautiful Jekyll.
baseurl: ""
url: "https://www.victorszoltysek.com" # the base hostname & protocol for your site
theme: minima
twitter_username: your-twitter
github_username:  your-github
